-- MySQL Script generated by MySQL Workbench
-- Sat Mar 27 01:51:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema realtimechat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema realtimechat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `realtimechat` DEFAULT CHARACTER SET utf8 ;
USE `realtimechat` ;

-- -----------------------------------------------------
-- Table `realtimechat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB DEFAULT charset=utf8;

INSERT INTO `realtimechat`.`users` (`id`, `name`, `email`) VALUES
(1, '', 'test01@gmail.com'),
(2, '', 'test01@hotmail.com'),
(3, '', 'test01@yahoo.com'),
(4, '', 'test01@outlook.com'),
(5, '', 'test01@go.buu.ac.th');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
